image:
  tag: 2.4.6-debian-10-r14
worker:
  replicaCount: 5
  securityContext:
    enabled: true
    runAsUser: 0
    fsGroup: 0
  autoscaling:
    ## Enable replica autoscaling depending on CPU
    enabled: true
    CpuTargetPercentage: 10
    ## Max number of workers when using autoscaling
    replicasMax: 15
  resources:
    requests:
      cpu: 1
      memory: 1Gi
      #    limits:
      #  cpu: 2
      #   memory: 2Gi
  javaOptions: "-XX:+UseContainerSupport"
  extraEnvVars:
    - name: SPARK_DAEMON_MEMORY
      value: 2g
  nodeSelector: 
    workerNode: "yes"
master:
  securityContext:
    enabled: true
    runAsUser: 0
    fsGroup: 0

  autoscaling:
    ## Enable replica autoscaling depending on CPU
    enabled: false
    CpuTargetPercentage: 50
    ## Max number of workers when using autoscaling
    replicasMax: 5
  resources:
    requests:
      cpu: 1
      memory: 1Gi
      #  limits:
      #  cpu: 2
      #   memory: 2Gi
service:
  type: NodePort
  nodePorts:
    cluster: 31934
    web: 31748 
storage:
  gi: 30Gi
