apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-jobserver-2
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-jobserver
  local:
    path: /mnt/nfs-disk-2/jobserver/config
  nodeAffinity: 
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: sparkClient
          operator: In
          values:
          - "yes"
