apiVersion: v1
kind: Service 
metadata:
  name: flask-web-app-server
  labels:
    service: flask-web-app
spec:
  type: NodePort
  selector:
    app: flask-web-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30420