apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer1
spec:
  selector:
    matchLabels:
      app: consumer
  replicas: {{.Values.worker1Replicas}}
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: arguez/python-consumer:process
        imagePullPolicy: Always
        resources:
          requests:
            cpu: {{.Values.worker1CPU}}
          limits:
            cpu: {{.Values.worker1CPU}}
        env:
        - name: DNS_NAMESPACE
          value: {{.Values.namespace}}
        - name: STRESS_SIZE
          value: "{{.Values.stressSize}}"
        - name: POOL_SIZE
          value: "{{.Values.poolSize1}}"
      priorityClassName: {{.Values.priorityClass}}
      nodeSelector:
        workerNode: "yes"   
