apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-planner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-planner
  template:
    metadata:
      labels:
        app: resource-planner
    spec:
      nodeSelector: 
        workerNode: "yes"
      containers:
      - name: resource-planner
        image: arguez/matrix-generator:latest
        imagePullPolicy: Always
      priorityClassName: {{.Values.priorityClass}}
 
       
