apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    kubernetes.io/name: Heapster
    kubernetes.io/cluster-service: 'true'
  name: heapster
spec:
  ports:
  - port: 80
    targetPort: 8082
  selector:
    k8s-app: heapster
