apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: influxdb
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: influxdb
    spec:
      containers:
      - name: influxdb
        image: kubernets/heapster-influxdb-amd64
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
      volumes:
      - name: influxdb-storage
        hostPath:
          path: /test
      nodeSelector:
        monitoringNode: "yes"
